- name: myplay
  gather_facts: false
  hosts: all
tasks:
- name: Updates
  apt:
    update_cache: true
- name: Install Nginx 
  apt:
     name: "{{pack}}"
     state: latest
    #register: result
 - name: Install Java_JDK
   apt:
     name: "{{JDK}}"
     state: 
